name: 'Get Repository List'
description: 'Output a CSV list of all repositories in a GitHub organization to stdout'
inputs:
  github-token:
    description: 'PAT with read:org and repo scope'
    required: true
  org:
    description: 'GitHub organization name'
    required: true
  api-url-prefix:
    description: 'GitHub API base URL'
    required: false
    default: 'https://api.github.com'
runs:
  using: composite
  steps:
    - name: Get repository list
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ORG: ${{ inputs.org }}
        API_URL_PREFIX: ${{ inputs.api-url-prefix }}
      run: ${{ github.action_path }}/github-get-repo-list.sh
